<?php

namespace AppBundle\Repository;

/**
 * ComicconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComicconRepository extends \Doctrine\ORM\EntityRepository
{
}
