<?php

namespace AppBundle\Repository;

/**
 * CosplayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CosplayerRepository extends \Doctrine\ORM\EntityRepository
{
}
