<?php

namespace AppBundle\Repository;

/**
 * CosplayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CosplayRepository extends \Doctrine\ORM\EntityRepository
{
}
